name: biketracker
description: Вело трекер

version: 1.0.9+16

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  permission_handler:
  intl:
  http:
  path_provider:
  flutter_localization:
  flutter_launcher_icons:
  flutter_native_splash:
  package_info_plus:
  flutter_html:
  url_launcher:
  flutter_map:
  latlong2:
    # DB Access library
  sqflite:
  sqlite3_flutter_libs:
  sqflite_common_ffi:
  vector_map_tiles:
  geolocator:
  syncfusion_flutter_gauges:
  shared_preferences:
  win32:
  wakelock_plus:
  mask_text_input_formatter:
  reorderables:
  fl_chart:
  flutter_webrtc:
  flutter_background:
  sdp_transform:
  go_router:
  flutter_verification_code:
  auto_size_text:
  #audioplayers: ^6.5.0
  health: 13.1.1
  flutter_vibrate: ^1.4.0
  flutter_nearby_connections: ^1.1.2
  uuid: ^4.5.1
  flutter_antplus: ^0.6.8+19

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#5E7280"
  image: asset/logo.png
  android_12:
    image: asset/logo.png
    color: "#5E7280"


flutter_launcher_icons:
  ios: true
  android: true
  image_path: "asset/logo.png"
  remove_alpha_ios: true
  windows:
    generate: false
    image_path: "asset/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: false
    image_path: "asset/logo.png"

flutter:
  uses-material-design: true

  assets:
    - asset/
    - assets/

